name: "Issue Label Manager Action"
description: "Will update repo's labels based on data in JSON file located at $REPO/.github/labels.json"
author: "DesarrolloORT"
runs:
  using: node20
  main: dist/index.js
branding:
  icon: "upload"
  color: "green"
inputs:
  delete:
    description: "Will not delete any existing labels and will only modify / create them"
    required: false
    default: "false"
